name: "vipm-BuildViPackage"
author: "NEVSTOP"
description: "CICD Action for sync VIPM library"
branding:
  icon: "anchor"
  color: "green"

runs:
  using: "composite"

  steps:
    - id: build-vip
      uses: LV-APT/lvCICD@main
      with:
        LabVIEW_Version: ${{ inputs.LabVIEW_Version }}
        Architecture: ${{ inputs.Architecture }}
        Operation: vipm_OpenVIPM


